// (C) Pasha Malinnikov, mpa@cci.lg.ua

// Вы можете найти ответ и на свой вопрос. Заходите:
// Here you can find answer on your question too! Welcome:

//							http://www.cci.lg.ua/~mpa
//							~~~~~~~~~~~~~~~~~~~~~~~~~


#define PI					3.1415926535897

#include <windows.h>
#include <GL/gl.h>
#include <GL/glu.h>
#include <stdio.h>
#include <io.h>
#include <string.h>
#include <math.h>

void FreeTexture( GLuint texture );
